### ISSUE TITLE
Telegram send fail

### ISSUE THREAD

**Issue by Nigh** [ACAlexChen/multi-platform-message-forwarding#1]
```
2024-05-31 22:39:59 [I] loader reload plugin multi-platform-message-forwarding:1qkhzf
2024-05-31 22:40:17 [W] app Error: Telegram API error 400. Bad Request: chat not found
                            at _Internal.<computed> [as sendMessage] (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:78:17)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async TelegramMessageEncoder.flush (/koishi/node_modules/@satorijs/adapter-telegram/lib/index.cjs:581:24)
                            at async TelegramMessageEncoder.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:610:5)
                            at async Proxy.sendMessage (/koishi/node_modules/@satorijs/core/lib/index.cjs:340:22)
```

**Comment by Nigh** [comment]
The ID get from `Group Info` is different from get from API

For example, ID from group info is `2010026666`, if you get from API, it would be `-1002010026666`
